sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
matrix:
  fast_finish: true
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
before_install:
  - git config --global user.name "$GH_USER_NAME"
  - git config --global user.email "$GH_USER_EMAIL"
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  include:
    - stage: Release
      node_js: 8
      deploy:
        provider: script
        script:
          - yarn run build
          - yarn run codeclimate
          - yarn run semantic-release
          - yarn run jsdoc
          - yarn run gh-pages
        on:
          branch: master
