sudo: false
language: node_js
node_js:
  - 5
  - 4
matrix:
  fast_finish: true
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
before_script:
  - npm prune
script:
  - npm run clean
  - npm run lint
  - npm run cover
after_script: [ "${TRAVIS_BRANCH}" = "master" ] && .travis/after-all.sh
