version: '{build}'
build: off
deploy: off
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache -> package.json'
branches:
  only:
    - master
  except:
    - gh-pages
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm prune
  - npm install
test_script:
  - node --version
  - npm --version
  - cmd: npm test
